### ISSUE TITLE
title of webpage

### ISSUE THREAD

**Issue by Dominique-M** [TEIC/TEIGarage#22]
teigarage.tei-c.org/ still has OxGarage as content of the title element under head of the HTML page, wich is confusing for the user. (Comes as OxGarage above the page in the brower and as shortcut.) In div footer also, About and Feedback are still OxGarage.

**Comment by peterstadler** [comment]
Sorry for the confusion. At present teigarage.tei-c.org still runs OxGarage but will be replaced in short time!

**Comment by peterstadler** [comment]
Done! now teigarage = teigarage ;)

Maybe you'll need to refresh your browser cache but now https://teigarage.tei-c.org/ serves TEIGarage v1.0.0
