### ISSUE TITLE
Conversion to epub does not include extension

### ISSUE THREAD

**Issue by joeytakeda** [TEIC/TEIGarage#36]
Through the web interface (https://teigarage.tei-c.org), the conversion of a document into ePub3 outputs a file with the same name, but no extension. After renaming with `.epub` appended, the epub works as expected, but requires renaming before it can be opened (in Apple Books, at least). 

Sample files (with the TEI file appended with .txt for GitHub reasons) attached.

[teigarage.xml.txt](https://github.com/TEIC/TEIGarage/files/10161954/teigarage.xml.txt)
[teigarage.docx](https://github.com/TEIC/TEIGarage/files/10161958/teigarage.docx)

**Comment by anneferger** [comment]
Thank you for opening this issue! Yes there was some configuration missing, I will do some testing now and hope the extension is set correctly now.

**Comment by peterstadler** [comment]
Updated TEIGarage deployed at teigarage.tei-c.org
