### ISSUE TITLE
add link to swagger

### ISSUE THREAD

**Issue by csae8092** [TEIC/TEIGarage#38]
Have you ever considered to add a link to your swagger api docs (https://teigarage.tei-c.org/ege-webservice/) to TEIGarage's start page?

**Comment by anneferger** [comment]
Yes, that is a good idea, thank you, I will add it to the footer when adding the version number in https://github.com/TEIC/TEIGarage/issues/23

**Comment by anneferger** [comment]
Done at https://teigarage.tei-c.org
